version: '3.7'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8001:8000

  db:
    image: postgres:11-alpine
    env_file:
      - docker-compose.env
    volumes:
      - db-data:/var/lib/postgresql/data
  # web:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile

volumes:
  db-data:
