version: '3.7'

services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8001:8000

  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      